import type { Metadata } from "next";
import Topbar from "@/components/topbar/Topbar";
import Footer from "@/components/footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <Topbar />
      {children}
      <Footer />
    </div>
  );
}
